name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - master
      - 'releases/*'

permissions:
  id-token: write
  contents: write

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run all
  test-new: # make sure the action works with a brand-new image tag
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls
      - name: Create shared Docker Image Tag
        id: create-tag
        uses: ./
        with:
          new-image-tag: "test-tag:${{ github.run_number }}"
          token: "${{ secrets.PERSONAL_TOKEN }}"
      - name: Print Docker Image Tag to use
        run: |
          echo image-tag ${{ steps.create-tag.outputs.image-tag }}
          echo found ${{ steps.create-tag.outputs.found }}
  test-existing: # make sure the action works with an existing image tag
    runs-on: ubuntu-latest
    needs: [test-new]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create shared Docker Image Tag
        id: reuse-tag
        uses: ./
        with:
          new-image-tag: "test-tag:${{ github.run_number }}"
          token: "${{ secrets.PERSONAL_TOKEN }}"
      - name: Print Docker Image Tag to use
        run: |
          echo image-tag ${{ steps.reuse-tag.outputs.image-tag }}
          echo found ${{ steps.reuse-tag.outputs.found }}
